### ISSUE TITLE
NextJS 13 and app dir (loader issues, e.g tailwind)

### ISSUE THREAD

**Issue by jackblackCH** [PiwikPRO/next-piwik-pro#15]
By following the instructions for NextJS it basically works but it missconfigures other loaders, e.g Tailwind.

So by adding 
```
/** @type {import('next').NextConfig} */

const withTM = require('next-transpile-modules')(['@piwikpro/next-piwik-pro'])
const nextConfig = {
  /* Your Next.js config */
}
module.exports = withTM(nextConfig)
```

and then `npm run dev`

```
- error ./app/globals.css
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @tailwind base;
| @tailwind components;
| @tailwind utilities;

Import trace for requested module:
./app/globals.css
```

**Comment by rgembalik** [comment]
@jackblackCH 
Living it here for future generations, because we've had the same problem:

Next 13+ doesn't require `next-transpile-modules` as it was replaced by a simple option in `next.config.js`:

```js
transpilePackages: ['@piwikpro/next-piwik-pro'],
```

Once you have that added, you need to use `<PiwikProProvider>` as per [docs](https://developers.piwik.pro/en/latest/data_collection/web/frameworks/Piwik_PRO_Library_for_NextJS.html), BUT bear in mind that it has to be in a client component (e.g. files with `'use client'` at the beginning of the file.

That's it!

**Comment by lysy-vlc** [comment]
Issue closed cause Next >= 13 is oficially supported with it's app directory

**Comment by fikkatra** [comment]
@rgembalik  what do you mean "it has to be in a client component"? The docs mention it should be placed in layout, which definitely should not be a client component. How to add the provider without rendering the entire app on the client?

**Comment by rgembalik** [comment]
@fikkatra I wouldn't read into it too much. Back then App directory wasn't supported and the provider was lacking "use client", so it has do be placed in a client component to be correctly pushed into client bundle. 

But that was before v2 was released. Nowadays, with v3 of the library, I don't think this workaround is needed anymore.
